### ISSUE TITLE
Release checklist for 0.4

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/poppy#132]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mperrin](https://github.com/mperrin)**
_Thursday Nov 19, 2015 at 22:37 GMT_
_Originally opened as https://github.com/mperrin/poppy/issues/132_

----

- [x] documentation #131 
- [x] bump version numbers
- [x] new pypi package
- [x] new docs on pythonhosted

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Friday Nov 20, 2015 at 02:43 GMT_

----

FYI to @josePhoenix - As of commit faf3e56 I think `poppy` is all ready to go. I am just going to hold off on pulling the trigger in case any last minute minor fixes are needed in the course of polishing the `webbpsf` release.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Friday Nov 20, 2015 at 02:46 GMT_

----

Sounds good.

The only other thing I can think of is whether you want to fiddle with the way the `Instrument.display()` or `Instrument.calcPSF(display=True)` plots look. That might not be worth the trouble, because I think at least one of those is totally overridden in WebbPSF anyway.
