### ISSUE TITLE
Release planning / prioritization for 0.5

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/poppy#163]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mperrin](https://github.com/mperrin)**
_Thursday Apr 21, 2016 at 22:06 GMT_
_Originally opened as https://github.com/mperrin/poppy/issues/163_

----

There are a bunch of substantial enhancements & refactoring tasks on the to-do list for 0.5, and the question is how much can get done before the AAS meeting (that deadline being driven by needing to release the next WebbPSF then). 
- #158 the refactoring of getPhasor  (this is now basically ready to go in PR #162, pending agreement from the rest of everyone that my revised API looks OK.  )
- #129 for anti-aliased apertures (work in progress, does not work yet)
- #145 for astropy.units usage (work in progress, does not work yet)
- #154 for cleaning up how plane types are implemented (work in progress, does not work yet)

Of the latter 3, I suspect I will only have time to do significant work on one or _maybe_ two over the course of the next month. So the questions to you all (@josePhoenix, @neilzim, @douglase) are: 
1. How would you prioritize between #129, #145, and #154? Let's say I only have time to get one done in 0.5, which would it be?   My personal preference is probably #145 or #154 since those would have the most impact on API changes and we're already mucking with the API given #158. But #129 has the most impact on numerical accuracy. 
2. Does anyone expect to have time to contribute to any of those?   (This question is directed more at STScI folks than at @douglase since I know he's got a thesis to finish up)  We should chat sometime soon IRL about dev priorities for poppy vs webbpsf too, and figure out what's really feasible to get into webbpsf 0.5.

**Comment by mperrin** [comment]
<a href="https://github.com/douglase"><img src="https://avatars1.githubusercontent.com/u/1025951?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [douglase](https://github.com/douglase)**
_Friday Apr 22, 2016 at 14:23 GMT_

----

For question 1: my ordering would be: #145,#129,#154. Units add flexibility and it has the larger impact on the API, while aliasing noticeably impacts performance. #154 doesn't seem like it adds functionality and might be tricky to implement without breaking existing systems.

For question 2: Thanks for the excuse, I am indeed still writing. The end is in sight (if not _precisely_ defined)...

I'd also like to make sure further aberrated wavefronts don't fall off our radar (#1, #92).

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Monday May 23, 2016 at 02:05 GMT_

----

- [x]  #158 implemented in PR #162 
- [x]  #145 implements in PR #165
- [ ]  #129 partially implemented in branch `subpixel_geometry` but not going to see any more progress in time for the next release. 
- [ ]  Punting on #154
