### ISSUE TITLE
Release to-do, 0.9.1

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/poppy#359]
- [x] Update release notes in docs with all PRs since Nov 25
- [x] Update list of contributors
- [x] Update version number
- [x] Release -> GitHub, pypi, conda

**Comment by mperrin** [comment]
fyi @shanosborne
